[project]
name = "nwfsc-wcgbts-bathy-processor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jim Fellows", email = "james.fellows@noaa.gov" }
]
requires-python = ">=3.13.2"
dependencies = [
    "echopype>=0.11.1",
    "folium>=0.20.0",
    "geopandas>=1.1.4",
    "h5py>=3.16.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "rasterio>=1.5.1",
    "shapely>=2.1.2",
    "xarray>=2026.7.0",
]

[project.scripts]
bathy-processor = "nwfsc_wcgbts_bathy_processor.cli:main"

[build-system]
requires = ["uv_build>=0.11.30,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
